version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: status_mysql
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 25s


  app:
    build:
      context: ./app
    container_name: aplicacao_app
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "5000:5000"

    volumes:
      - ./app:/app

volumes:
  mysql_data: